name: main
on: [push]
jobs:
  build_and_test__ubuntu_18_04:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install -yqq wget build-essential cmake
      - run: mkdir build && cd build && cmake .. && make
      - run: cd build && ctest
  build_and_test__ubuntu_20_04:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install -yqq wget build-essential cmake
      - run: mkdir build && cd build && cmake .. && make
      - run: cd build && ctest