name: main
on: [push]
jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install -yqq wget build-essential cmake
      - run: mkdir build && cd build && cmake .. && make
      - run: cd build && ctest --verbose